resolver: nightly-2019-09-21
packages:
- .
- ./hie-compat/
extra-deps:
- aeson-1.4.6.0
- haskell-lsp-0.22.0.0
- haskell-lsp-types-0.22.0.0
- lsp-test-0.11.0.6
- hie-bios-0.7.1@rev:2
- implicit-hie-0.1.2.0
- implicit-hie-cradle-0.2.0.1
- fuzzy-0.1.0.0
- regex-pcre-builtin-0.95.1.1.8.43
- regex-base-0.94.0.0
- regex-tdfa-1.3.1.0
- shake-0.18.5
- parser-combinators-1.2.1
- haddock-library-1.8.0
# Had to make a hacky fork of haddock-api 2.22.0 that uses "sandboxed" haddock-library-1.7.0 dependency
# so it doesn't collide with of haddock-library-1.8.0
# TODO: fix upstream, use package
# TODO: can we link haddock-library-1.7.0 only to haddock-api without the hack?
# TOOD: or just use haddock-library-1.7.0 for all ? but it's older and breaks some tests
- github: DunetsNM/haddock
  commit: a2b6a8f97458a4e135738294104304151ea1c94f
  subdirs:
    - haddock-api
    - haddock-library-sandbox
- tasty-rerun-1.1.17
- ghc-check-0.5.0.1
- extra-1.7.2

nix:
  packages: [zlib]

ghc-options:
  ghcide: -DSTACK
  "$everything": -haddock
