resolver: nightly-2019-09-21
packages:
- .
- ./hie-compat/
extra-deps:
- aeson-1.4.6.0
- haskell-lsp-0.22.0.0
- haskell-lsp-types-0.22.0.0
- lsp-test-0.11.0.6
- hie-bios-0.7.1@rev:2
- implicit-hie-0.1.2.0
- implicit-hie-cradle-0.2.0.1
- fuzzy-0.1.0.0
- regex-pcre-builtin-0.95.1.1.8.43
- regex-base-0.94.0.0
- regex-tdfa-1.3.1.0
- shake-0.18.5
- parser-combinators-1.2.1
- haddock-library-1.7.0
# haddock-api-2.22.0 doesn't compile. TODO: fix upstream, use package
- github: haskell/haddock
  commit: 1f704e30d5f40fa5113045b252c0e48aebd842be
  subdirs:
    - haddock-api
- tasty-rerun-1.1.17
- ghc-check-0.5.0.1
- extra-1.7.2

nix:
  packages: [zlib]

ghc-options:
  ghcide: -DSTACK
  "$everything": -haddock
